import React, { useState } from "react";
import Head from 'next/head';
import axios from "axios";
import Link from 'next/link'

const create = () => {
    const [firstName, setFirstName] = useState("");
    const [lastName, setLastName] = useState("");
    const [checkbox, setCheckbox] = useState(false);
  
    
    const postData = (e) => {
      e.preventDefault();
      if (!firstName & !lastName) {
        window.alert("please fill data");
      } else if (!firstName) {
        window.alert("please fill firstName");
      } else if (!lastName) {
        window.alert("please fill lastName");
      } else {
        axios.post(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata`, {
          firstName,
          lastName,
          checkbox
        });
        setLastName("");
        setFirstName("");
        
      }
    };
  return (
    <div>
        <Head>
        <title>Create | todo-list</title>
        <meta name="description" content="Todo-list Generated by create next app" />
        </Head>
        <main>
        <div>
            <div className="text-center pt-4">
                <Link href='/'>
                <button className="btn btn-primary ">Check All Data</button>
                </Link>
            </div>
            <div className="row d-flex justify-content-center">
            <form className="text-start p-4 col-md-6">
                <div className="mb-3">
                <label className="form-label">First Name</label>
                <input
                    type="text"
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    className="form-control"
                />
                </div>
                <div className="mb-3">
                <label className="form-label">Last Name</label>
                <input
                    type="text"
                    value={lastName}
                    onChange={(e) => setLastName(e.target.value)}
                    className="form-control"
                />
                </div>
                <div className="mb-3 form-check">
                <input
                    type="checkbox"
                    value={checkbox}
                    onChange={(e) => setCheckbox(!checkbox)}
                    className="form-check-input"
                />
                <label className="form-check-label">Check me out</label>
                </div>

                <Link href='/'>
                <button onClick={postData} type="submit" className="btn btn-primary">
                    submit
                </button>
                </Link>
            </form>

            </div>
            
         </div>
        </main>
    </div>
  )
}

export default create;