import React, { useState, useEffect, useContext } from "react";
import Head from 'next/head';
import Link from 'next/link';
import axios from "axios";
import { store } from "./_app";







export default function Home() {

  const [ID, setID] = useContext(store);

  const [APIData, setAPIData] = useState([]);
  useEffect(() => {
    axios
      .get(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata`)
      .then((response) => {
        setAPIData(response.data);
      });
  }, []);

  const onDelete = (id) => {
    axios
      .delete(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata/${id}`)
      .then(() => {
        getData();
      });
  };

  const getData = () => {
    axios
      .get(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata`)
      .then((getData) => {
        setAPIData(getData.data);
      });
  };
  
  return (
    <>
      <Head>
        <title>Home | todo-list</title>
        <meta name="description" content="Todo-list Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container'>
      <div className="p-4">
      <div className="text-center p-4">
        <Link href='/create'>
          <button className="btn btn-primary ">Create a new</button>
        </Link>
      </div>

      <h2 className="text-center pt-2">Users List</h2>
      <table className="table ">
        <thead>
          <tr>
            <th scope="col">FirstName</th>
            <th scope="col">LastName</th>
            <th scope="col">Checked</th>
            <th scope="col">Update</th>
          </tr>
        </thead>
        <tbody>
          {APIData.map((data) => {
            return (
              <tr key={data.id}>
                <td>{data.firstName}</td>
                <td>{data.lastName}</td>
                <td>{data.checkbox ? "Checked" : "Unchecked"}</td>
                <td>
                  <Link href='/update'>
                    <button
                      onClick={() => setID(data.id)}
                      className="btn btn-warning"
                    >
                      Update
                    </button>
                  </Link>
                </td>
                <td>
                  <button
                    onClick={() => onDelete(data.id)}
                    type="button"
                    className="btn btn-danger"
                  >
                    delete
                  </button>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
        
      </main>
    </>
  )
}
