import React, {useState, useEffect, useContext} from 'react';
import Link from 'next/link';
import Head from 'next/head';
import axios from "axios";
import { store } from "./_app";

const update = () => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [checkbox, setCheckbox] = useState(false);
  const [ID, setID] = useContext(store);
  console.log(ID);

  

  useEffect(() => {
    axios
      .get(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata/${ID}`)
      .then((response) => {
        setFirstName(response.data.firstName);
        setLastName(response.data.lastName);
        setCheckbox(response.data.checkbox);
      });
  }, []);

  const postData = () => {
    axios.put(`https://638457103fa7acb14ff1e080.mockapi.io/fakedata/${ID}`, {
      firstName,
      lastName,
      checkbox
    });
  };
  return (
    <div>
        <Head>
        <title>update | todo-list</title>
        <meta name="description" content="Todo-list Generated by create next app" />
        </Head>
        <main className='container'>
        <div>
          <h2 className="text-center pt-4">Update a value here</h2>
          <form className="text-start p-4">
            <div className="mb-3">
              <label className="form-label">First Name</label>
              <input
                type="text"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                className="form-control"
              />
            </div>
            <div className="mb-3">
              <label className="form-label">Last Name</label>
              <input
                type="text"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                className="form-control"
                required
              />
            </div>
            <div className="mb-3 form-check">
              <input
                type="checkbox"
                value={checkbox}
                onChange={(e) => setCheckbox(!checkbox)}
                className="form-check-input"
              />
              <label className="form-check-label">Check me out</label>
            </div>
            <Link href='/'>
              <button onClick={postData} type="submit" className="btn btn-primary">
                Update
              </button>
            </Link>
          </form>
         </div>
        </main>
        
    </div>
  )
}

export default update